FROM ubuntu:21.04

RUN apt-get update

RUN apt-get install -yy --no-install-recommends \
        software-properties-common \
	dirmngr \
	gnupg-agent

RUN apt-get update --fix-missing

RUN apt-get install -yy \
  asciidoctor \
  autoconf \
  automake \
  ccache \
  clang \
  gcc \
  gcc-10 \
  git \
  graphviz \
  iproute2 \
  kmod \
  libcli-dev \
  libconfig-dev \
  libcunit1-dev \
  libdpdk-dev \
  libibverbs-dev \
  libnuma-dev \
  libpcap-dev \
  libssl-dev \
  libstdc++-10-dev \
  libtool \
  mscgen \
  net-tools \
  python3-pip \
  ruby-dev \
  sudo \
  xsltproc && \
pip3 install coverage
